server:
  port: 8081

spring:
  application:
    name: cards
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "configserver:http://localhost:8888/"
    # If the above does not work, try the following - https://stackoverflow.com/a/78598168
    # add optional:configServer:http://localhost:8888/acounts/default
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# to enable actuator and expose all endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*" # '*' means all

#####################################
##                                 ##
## These are moved to ConfigServer ##
##                                 ##
#####################################

#  config:
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"
#    profiles:
#      active:
#        - "qa"
#
#  build:
#    version: "3.0"
#
#  cards:
#    message: "Welcome to EazyBank cards related local APIs "
#    contactDetails:
#      name: "Dragos Lech - Developer"
#      email: "dragos@eazybank.com"
#    onCallSupport:
#      - (412) 419-3491
#      - (915) 382-1932